// This file contains mock data to expand our playlists for pagination demonstration

export const additionalPlaylists = [
  {
    id: "9",
    name: "Summer Vibes",
    description: "The perfect soundtrack for your summer featuring upbeat tracks from our top artists",
    image: "https://placehold.co/600x600?text=Summer+Vibes",
    slug: "summer-vibes",
    type: "Themed Playlists",
    created: "2024-03-01",
    totalTracks: 22,
    owner: "Denise Carlos - RMPG,Uganda",
  },
  {
    id: "10",
    name: "Acoustic Sessions",
    description: "Stripped-down acoustic performances showcasing the raw talent of our artists",
    image: "https://placehold.co/600x600?text=Acoustic+Sessions",
    slug: "acoustic-sessions",
    type: "Themed Playlists",
    created: "2024-03-05",
    totalTracks: 18,
    owner: "Denise Carlos - RMPG,Uganda",
  },
  {
    id: "11",
    name: "Throwback Classics",
    description: "A nostalgic journey through the classic hits from our legendary artists",
    image: "https://placehold.co/600x600?text=Throwback+Classics",
    slug: "throwback-classics",
    type: "Themed Playlists",
    created: "2024-03-10",
    totalTracks: 25,
    owner: "Denise Carlos - RMPG,Uganda",
  },
  {
    id: "12",
    name: "Workout Mix",
    description: "High-energy tracks to fuel your workout and keep you motivated",
    image: "https://placehold.co/600x600?text=Workout+Mix",
    slug: "workout-mix",
    type: "Themed Playlists",
    created: "2024-03-15",
    totalTracks: 20,
    owner: "Denise Carlos - RMPG,Uganda",
  },
  {
    id: "13",
    name: "Chill Vibes",
    description: "Relaxing tracks perfect for unwinding after a long day",
    image: "https://placehold.co/600x600?text=Chill+Vibes",
    slug: "chill-vibes",
    type: "Themed Playlists",
    created: "2024-03-20",
    totalTracks: 15,
    owner: "Denise Carlos - RMPG,Uganda",
  },
  {
    id: "14",
    name: "Rising Stars",
    description: "Discover the next generation of talent from our newest signed artists",
    image: "https://placehold.co/600x600?text=Rising+Stars",
    slug: "rising-stars",
    type: "Themed Playlists",
    created: "2024-03-25",
    totalTracks: 12,
    owner: "Denise Carlos - RMPG,Uganda",
  },
  {
    id: "15",
    name: "Collaboration Hits",
    description: "The best collaborations between our artists creating magical musical moments",
    image: "https://placehold.co/600x600?text=Collaboration+Hits",
    slug: "collaboration-hits",
    type: "Themed Playlists",
    created: "2024-04-01",
    totalTracks: 16,
    owner: "Denise Carlos - RMPG,Uganda",
  },
  {
    id: "16",
    name: "Inspirational Anthems",
    description: "Uplifting songs to inspire and motivate you through any challenge",
    image: "https://placehold.co/600x600?text=Inspirational+Anthems",
    slug: "inspirational-anthems",
    type: "Themed Playlists",
    created: "2024-04-05",
    totalTracks: 14,
    owner: "Denise Carlos - RMPG,Uganda",
  },
]

